
export const products = [
    {
      sku: "HC-SHMP-001",
      name: "Nourishing Shampoo",
      brand: "L'Oréal Professionnel",
      category: "Hair Care",
      stock: 75,
      price: 25.50,
    },
    {
      sku: "HC-COND-001",
      name: "Repairing Conditioner",
      brand: "Kerastase",
      category: "Hair Care",
      stock: 60,
      price: 35.00,
    },
    {
      sku: "HS-SPRAY-001",
      name: "Strong Hold Hairspray",
      brand: "Redken",
      category: "Styling",
      stock: 90,
      price: 22.00,
    },
    {
      sku: "SC-CLNS-001",
      name: "Gentle Face Cleanser",
      brand: "Dermalogica",
      category: "Skin Care",
      stock: 45,
      price: 40.00,
    },
    {
      sku: "NC-POL-001",
      name: "Classic Red Nail Polish",
      brand: "OPI",
      category: "Nail Care",
      stock: 120,
      price: 10.50,
    },
    {
      sku: "NC-POL-002",
      name: "Nude Nail Polish",
      brand: "Essie",
      category: "Nail Care",
      stock: 8,
      price: 9.00,
    },
    {
      sku: "HC-MASK-001",
      name: "Hydrating Hair Mask",
      brand: "Moroccanoil",
      category: "Hair Care",
      stock: 30,
      price: 48.00,
    },
    {
      sku: "SC-SERUM-001",
      name: "Vitamin C Serum",
      brand: "SkinCeuticals",
      category: "Skin Care",
      stock: 25,
      price: 166.00,
    },
     {
      sku: "ST-GEL-001",
      name: "Styling Gel",
      brand: "American Crew",
      category: "Styling",
      stock: 50,
      price: 18.00,
    },
    {
      sku: "HC-OIL-001",
      name: "Argan Oil Treatment",
      brand: "Moroccanoil",
      category: "Hair Care",
      stock: 40,
      price: 44.00,
    },
];
