
export const salons = [
  {
    id: "salon_01",
    name: "Downtown Studio",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: "salon_02",
    name: "Uptown Oasis",
    address: "456 Oak Ave, Anytown, USA",
  },
];

export const users = [
  {
    id: "user_01",
    name: "Super Admin",
    email: "super@admin.com",
    password: "password",
    avatar: "https://picsum.photos/seed/super-admin/100/100",
    role: "SUPER_ADMIN",
    salonId: null,
  },
  {
    id: "user_02",
    name: "Salon Admin",
    email: "salon@admin.com",
    password: "password",
    avatar: "https://picsum.photos/seed/salon-admin/100/100",
    role: "SALON_ADMIN",
    salonId: "salon_01",
  },
  {
    id: "user_03",
    name: "Uptown Admin",
    email: "uptown@admin.com",
    password: "password",
    avatar: "https://picsum.photos/seed/uptown-admin/100/100",
    role: "SALON_ADMIN",
    salonId: "salon_02",
  },
];

export const services = [
  // Discounts
  {
    id: "promo_01",
    name: "20% Off First Visit",
    description: "New clients get 20% off any single service on their first visit.",
    price: "Varies",
    originalPrice: null,
    duration: null,
    image: "https://picsum.photos/seed/promo-new/600/400",
    category: "Discount",
  },
  {
    id: "promo_02",
    name: "Refer a Friend, Get $25 Off",
    description: "Refer a new client and you both get $25 off your next service.",
    price: "$25 Credit",
    originalPrice: null,
    duration: null,
    image: "https://picsum.photos/seed/promo-refer/600/400",
    category: "Discount",
  },
  // Deals
  {
    id: "deal_01",
    name: "Mani-Pedi Combo",
    description: "Our Luxury Manicure and Spa Pedicure together at a special price.",
    price: 100.0,
    originalPrice: 110.0,
    duration: 105,
    image: "https://picsum.photos/seed/mani-pedi/600/400",
    category: "Deal",
  },
  {
    id: "deal_02",
    name: "Cut, Color & Condition",
    description: "A complete hair refresh: Signature Haircut, Full Color, and a Deep Conditioning Treatment.",
    price: 275.0,
    originalPrice: 290.0,
    duration: 210,
    image: "https://picsum.photos/seed/hair-package/600/400",
    category: "Deal",
  },
  // Individual Services
  {
    id: "svc_01",
    name: "Signature Haircut & Style",
    description: "A customized haircut designed by your stylist to fit your individual style and preferences, includes a relaxing shampoo and professional styling.",
    price: 85.0,
    originalPrice: null,
    duration: 60,
    image: "https://picsum.photos/seed/haircut/600/400",
    category: "Service",
  },
  {
    id: "svc_02",
    name: "Full Color & Gloss",
    description: "Permanent or semi-permanent color application from roots to ends, finished with a gloss for shine and vibrancy.",
    price: 150.0,
    originalPrice: null,
    duration: 120,
    image: "https://picsum.photos/seed/hair-color/600/400",
    category: "Service",
  },
  {
    id: "svc_03",
    name: "Balayage / Ombré",
    description: "A technique for highlighting hair in which the dye is painted on in such a way as to create a graduated, natural-looking effect.",
    price: 250.0,
    originalPrice: null,
    duration: 180,
    image: "https://picsum.photos/seed/balayage/600/400",
    category: "Service",
  },
  {
    id: "svc_04",
    name: "Luxury Manicure",
    description: "Includes nail shaping, cuticle care, a relaxing hand massage, and a polish of your choice. A true treat for your hands.",
    price: 45.0,
    originalPrice: null,
    duration: 45,
    image: "https://picsum.photos/seed/manicure/600/400",
    category: "Service",
  },
  {
    id: "svc_05",
    name: "Spa Pedicure",
    description: "Relax in our massage chairs while we pamper your feet. Includes a warm soak, exfoliation, nail care, massage, and polish.",
    price: 65.0,
    originalPrice: null,
    duration: 60,
    image: "https://picsum.photos/seed/pedicure/600/400",
    category: "Service",
  },
  {
    id: "svc_06",
    name: "Deep Conditioning Treatment",
    description: "An intense conditioning treatment to restore moisture, protein, and shine to dry, damaged hair. Add-on to any hair service.",
    price: 55.0,
    originalPrice: null,
    duration: 30,
    image: "https://picsum.photos/seed/hair-mask/600/400",
    category: "Service",
  },
];


export const staff = [
  { id: "staff_01", name: "Jessica Miller", department: "Stylist", salonId: "salon_01" },
  { id: "staff_02", name: "Michael Chen", department: "Stylist", salonId: "salon_01" },
  { id: "staff_03", name: "Emily Rodriguez", department: "Nail Artist", salonId: "salon_02" },
  { id: "staff_04", name: "David Wilson", department: "Nail Artist", salonId: "salon_02" },
  { id: "staff_05", name: "Olivia Brown", department: "Receptionist", salonId: "salon_01" },
  { id: "staff_06", name: "Daniel Green", department: "Assistant", salonId: "salon_02" },
];

export const departments = [
  "Stylist",
  "Nail Artist",
  "Esthetician",
  "Massage Therapist",
  "Receptionist",
  "Assistant",
  "Manager",
];

export const mockCustomers = [
  {
    id: "cust_01",
    phone: "+923001234567",
    name: "Sophia Davis",
    email: "sophia@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_02",
    phone: "+923217654321",
    name: "Liam Garcia",
    email: "liam@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_03",
    phone: "+14155551234",
    name: "Ava Johnson",
    email: "ava@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_04",
    phone: "+14155555678",
    name: "Noah Brown",
    email: "noah@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_05",
    phone: "+14155558765",
    name: "Isabella Smith",
    email: "isabella@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_06",
    phone: "+14155554321",
    name: "James Williams",
    email: "james@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_07",
    phone: "+16505551111",
    name: "Olivia Jones",
    email: "olivia.jones@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_08",
    phone: "+16505552222",
    name: "Benjamin Garcia",
    email: "benjamin.garcia@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_09",
    phone: "+16505553333",
    name: "Mia Martinez",
    email: "mia.martinez@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_10",
    phone: "+16505554444",
    name: "Ethan Rodriguez",
    email: "ethan.rodriguez@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_11",
    phone: "+16505555555",
    name: "Abigail Taylor",
    email: "abigail.taylor@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_12",
    phone: "+16505556666",
    name: "William Anderson",
    email: "william.anderson@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_13",
    phone: "+16505557777",
    name: "Charlotte Thomas",
    email: "charlotte.thomas@example.com",
    salonId: "salon_01",
  },
  {
    id: "cust_14",
    phone: "+16505558888",
    name: "Daniel White",
    email: "daniel.white@example.com",
    salonId: "salon_02",
  },
  {
    id: "cust_15",
    phone: "+16505559999",
    name: "Harper Harris",
    email: "harper.harris@example.com",
    salonId: "salon_01",
  },
];

export const appointments = [
  {
    id: "apt_01",
    salonId: "salon_01",
    customer: mockCustomers[0], // Sophia Davis
    service: "Balayage / Ombré",
    staff: "Jessica Miller",
    date: "2024-07-30",
    time: "09:00 AM",
    price: 250.0,
  },
  {
    id: "apt_02",
    salonId: "salon_01",
    customer: mockCustomers[1], // Liam Garcia
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-07-30",
    time: "10:00 AM",
    price: 85.0,
  },
  {
    id: "apt_03",
    salonId: "salon_02",
    customer: mockCustomers[2], // Ava Johnson
    service: "Luxury Manicure",
    staff: "Emily Rodriguez",
    date: "2024-07-30",
    time: "11:00 AM",
    price: 45.0,
  },
  {
    id: "apt_04",
    salonId: "salon_01",
    customer: mockCustomers[3], // Noah Brown
    service: "Full Color & Gloss",
    staff: "Jessica Miller",
    date: "2024-07-30",
    time: "12:00 PM",
    price: 150.0,
  },
  {
    id: "apt_05",
    salonId: "salon_02",
    customer: mockCustomers[4], // Isabella Smith
    service: "Spa Pedicure",
    staff: "David Wilson",
    date: "2024-07-30",
    time: "01:00 PM",
    price: 65.0,
  },
  {
    id: "apt_06",
    salonId: "salon_01",
    customer: mockCustomers[0], // Sophia Davis
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-08-01",
    time: "02:00 PM",
    price: 85.0,
  },
  {
    id: "apt_07",
    salonId: "salon_02",
    customer: mockCustomers[6], // Olivia Jones
    service: "Deep Conditioning Treatment",
    staff: "Emily Rodriguez",
    date: "2024-08-02",
    time: "09:00 AM",
    price: 55.0,
  },
  {
    id: "apt_08",
    salonId: "salon_01",
    customer: mockCustomers[7], // Benjamin Garcia
    service: "Balayage / Ombré",
    staff: "Jessica Miller",
    date: "2024-08-05",
    time: "10:00 AM",
    price: 250.0,
  },
  {
    id: "apt_09",
    salonId: "salon_02",
    customer: mockCustomers[8], // Mia Martinez
    service: "Luxury Manicure",
    staff: "David Wilson",
    date: "2024-08-10",
    time: "11:00 AM",
    price: 45.0,
  },
  {
    id: "apt_10",
    salonId: "salon_01",
    customer: mockCustomers[1], // Liam Garcia
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-08-15",
    time: "01:00 PM",
    price: 85.0,
  },
  {
    id: "apt_11",
    salonId: "salon_02",
    customer: mockCustomers[10], // Abigail Taylor
    service: "Spa Pedicure",
    staff: "David Wilson",
    date: "2024-07-30",
    time: "02:00 PM",
    price: 65.0,
  },
  {
    id: "apt_12",
    salonId: "salon_01",
    customer: mockCustomers[0], // Sophia Davis
    service: "Full Color & Gloss",
    staff: "Jessica Miller",
    date: "2024-07-20",
    time: "03:00 PM",
    price: 150.0,
  },
  {
    id: "apt_13",
    salonId: "salon_01",
    customer: mockCustomers[12], // Charlotte Thomas
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-07-30",
    time: "04:00 PM",
    price: 85.0,
  },
  {
    id: "apt_14",
    salonId: "salon_02",
    customer: mockCustomers[13], // Daniel White
    service: "Balayage / Ombré",
    staff: "Emily Rodriguez",
    date: "2024-08-01",
    time: "09:00 AM",
    price: 250.0,
  },
  {
    id: "apt_15",
    salonId: "salon_02",
    customer: mockCustomers[14], // Harper Harris
    service: "Luxury Manicure",
    staff: "David Wilson",
    date: "2024-8-01",
    time: "10:00 AM",
    price: 45.0,
  },
];
