
export const salons = [
  {
    id: "salon_01",
    name: "Downtown Studio",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: "salon_02",
    name: "Uptown Oasis",
    address: "456 Oak Ave, Anytown, USA",
  },
];

export const users = [
  {
    id: "user_01",
    name: "Super Admin",
    email: "super@admin.com",
    password: "password",
    avatar: "https://picsum.photos/seed/super-admin/100/100",
    role: "SUPER_ADMIN",
    salonId: null,
  },
  {
    id: "user_02",
    name: "Salon Admin",
    email: "salon@admin.com",
    password: "password",
    avatar: "https://picsum.photos/seed/salon-admin/100/100",
    role: "SALON_ADMIN",
    salonId: "salon_01",
  },
];

export const services = [
  // Discounts
  {
    id: "promo_01",
    name: "20% Off First Visit",
    description: "New clients get 20% off any single service on their first visit.",
    price: "Varies",
    originalPrice: null,
    duration: null,
    image: "https://picsum.photos/seed/promo-new/600/400",
    category: "Discount",
  },
  {
    id: "promo_02",
    name: "Refer a Friend, Get $25 Off",
    description: "Refer a new client and you both get $25 off your next service.",
    price: "$25 Credit",
    originalPrice: null,
    duration: null,
    image: "https://picsum.photos/seed/promo-refer/600/400",
    category: "Discount",
  },
  // Deals
  {
    id: "deal_01",
    name: "Mani-Pedi Combo",
    description: "Our Luxury Manicure and Spa Pedicure together at a special price.",
    price: 100.0,
    originalPrice: 110.0,
    duration: 105,
    image: "https://picsum.photos/seed/mani-pedi/600/400",
    category: "Deal",
  },
  {
    id: "deal_02",
    name: "Cut, Color & Condition",
    description: "A complete hair refresh: Signature Haircut, Full Color, and a Deep Conditioning Treatment.",
    price: 275.0,
    originalPrice: 290.0,
    duration: 210,
    image: "https://picsum.photos/seed/hair-package/600/400",
    category: "Deal",
  },
  // Individual Services
  {
    id: "svc_01",
    name: "Signature Haircut & Style",
    description: "A customized haircut designed by your stylist to fit your individual style and preferences, includes a relaxing shampoo and professional styling.",
    price: 85.0,
    originalPrice: null,
    duration: 60,
    image: "https://picsum.photos/seed/haircut/600/400",
    category: "Service",
  },
  {
    id: "svc_02",
    name: "Full Color & Gloss",
    description: "Permanent or semi-permanent color application from roots to ends, finished with a gloss for shine and vibrancy.",
    price: 150.0,
    originalPrice: null,
    duration: 120,
    image: "https://picsum.photos/seed/hair-color/600/400",
    category: "Service",
  },
  {
    id: "svc_03",
    name: "Balayage / Ombré",
    description: "A technique for highlighting hair in which the dye is painted on in such a way as to create a graduated, natural-looking effect.",
    price: 250.0,
    originalPrice: null,
    duration: 180,
    image: "https://picsum.photos/seed/balayage/600/400",
    category: "Service",
  },
  {
    id: "svc_04",
    name: "Luxury Manicure",
    description: "Includes nail shaping, cuticle care, a relaxing hand massage, and a polish of your choice. A true treat for your hands.",
    price: 45.0,
    originalPrice: null,
    duration: 45,
    image: "https://picsum.photos/seed/manicure/600/400",
    category: "Service",
  },
  {
    id: "svc_05",
    name: "Spa Pedicure",
    description: "Relax in our massage chairs while we pamper your feet. Includes a warm soak, exfoliation, nail care, massage, and polish.",
    price: 65.0,
    originalPrice: null,
    duration: 60,
    image: "https://picsum.photos/seed/pedicure/600/400",
    category: "Service",
  },
  {
    id: "svc_06",
    name: "Deep Conditioning Treatment",
    description: "An intense conditioning treatment to restore moisture, protein, and shine to dry, damaged hair. Add-on to any hair service.",
    price: 55.0,
    originalPrice: null,
    duration: 30,
    image: "https://picsum.photos/seed/hair-mask/600/400",
    category: "Service",
  },
];


export const staff = [
  { id: "staff_01", name: "Jessica Miller", salonId: "salon_01" },
  { id: "staff_02", name: "Michael Chen", salonId: "salon_01" },
  { id: "staff_03", name: "Emily Rodriguez", salonId: "salon_02" },
  { id: "staff_04", name: "David Wilson", salonId: "salon_02" },
];

export const mockCustomers = [
  {
    phone: "+923001234567",
    name: "Sophia Davis",
    email: "sophia@example.com",
  },
  {
    phone: "+923217654321",
    name: "Liam Garcia",
    email: "liam@example.com",
  },
];

export const appointments = [
  {
    id: "apt_01",
    salonId: "salon_01",
    customer: { name: "Sophia Davis", email: "sophia@example.com" },
    service: "Balayage / Ombré",
    staff: "Jessica Miller",
    date: "2024-07-30",
    time: "09:00 AM",
    price: 250.0,
  },
  {
    id: "apt_02",
    salonId: "salon_01",
    customer: { name: "Liam Garcia", email: "liam@example.com" },
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-07-30",
    time: "10:00 AM",
    price: 85.0,
  },
  {
    id: "apt_03",
    salonId: "salon_02",
    customer: { name: "Ava Johnson", email: "ava@example.com" },
    service: "Luxury Manicure",
    staff: "Emily Rodriguez",
    date: "2024-07-30",
    time: "11:00 AM",
    price: 45.0,
  },
  {
    id: "apt_04",
    salonId: "salon_01",
    customer: { name: "Noah Brown", email: "noah@example.com" },
    service: "Full Color & Gloss",
    staff: "Jessica Miller",
    date: "2024-07-30",
    time: "12:00 PM",
    price: 150.0,
  },
  {
    id: "apt_05",
    salonId: "salon_02",
    customer: { name: "Isabella Smith", email: "isabella@example.com" },
    service: "Spa Pedicure",
    staff: "David Wilson",
    date: "2024-07-30",
    time: "01:00 PM",
    price: 65.0,
  },
  {
    id: "apt_06",
    salonId: "salon_01",
    customer: { name: "James Williams", email: "james@example.com" },
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-08-01",
    time: "02:00 PM",
    price: 85.0,
  },
  {
    id: "apt_07",
    salonId: "salon_02",
    customer: { name: "Olivia Jones", email: "olivia.jones@example.com" },
    service: "Deep Conditioning Treatment",
    staff: "Emily Rodriguez",
    date: "2024-08-02",
    time: "09:00 AM",
    price: 55.0,
  },
  {
    id: "apt_08",
    salonId: "salon_01",
    customer: { name: "Benjamin Garcia", email: "benjamin.garcia@example.com" },
    service: "Balayage / Ombré",
    staff: "Jessica Miller",
    date: "2024-08-05",
    time: "10:00 AM",
    price: 250.0,
  },
  {
    id: "apt_09",
    salonId: "salon_02",
    customer: { name: "Mia Martinez", email: "mia.martinez@example.com" },
    service: "Luxury Manicure",
    staff: "David Wilson",
    date: "2024-08-10",
    time: "11:00 AM",
    price: 45.0,
  },
  {
    id: "apt_10",
    salonId: "salon_01",
    customer: { name: "Ethan Rodriguez", email: "ethan.rodriguez@example.com" },
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-08-15",
    time: "01:00 PM",
    price: 85.0,
  },
  {
    id: "apt_11",
    salonId: "salon_02",
    customer: { name: "Abigail Taylor", email: "abigail.taylor@example.com" },
    service: "Spa Pedicure",
    staff: "David Wilson",
    date: "2024-07-30",
    time: "02:00 PM",
    price: 65.0,
  },
  {
    id: "apt_12",
    salonId: "salon_01",
    customer: { name: "William Anderson", email: "william.anderson@example.com" },
    service: "Full Color & Gloss",
    staff: "Jessica Miller",
    date: "2024-07-30",
    time: "03:00 PM",
    price: 150.0,
  },
  {
    id: "apt_13",
    salonId: "salon_01",
    customer: { name: "Charlotte Thomas", email: "charlotte.thomas@example.com" },
    service: "Signature Haircut & Style",
    staff: "Michael Chen",
    date: "2024-07-30",
    time: "04:00 PM",
    price: 85.0,
  },
  {
    id: "apt_14",
    salonId: "salon_02",
    customer: { name: "Daniel White", email: "daniel.white@example.com" },
    service: "Balayage / Ombré",
    staff: "Emily Rodriguez",
    date: "2024-08-01",
    time: "09:00 AM",
    price: 250.0,
  },
  {
    id: "apt_15",
    salonId: "salon_02",
    customer: { name: "Harper Harris", email: "harper.harris@example.com" },
    service: "Luxury Manicure",
    staff: "David Wilson",
    date: "2024-08-01",
    time: "10:00 AM",
    price: 45.0,
  },
];
